name: MTA GTFS Static

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest
    concurrency:
      group: mta-rtf-static-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            dlt_mta_rtf/requirements.txt

      - name: Setup venv and install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r dlt_mta_rtf/requirements.txt

      - name: Write GCP SA key to file
        run: |
          echo "$GCP_SA_KEY_JSON" > sa.json
        env:
          GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Run static pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID || secrets.gcp_project_id }}
          SOURCES__MTA_GTFS_STATIC__ZIP_URL: ${{ secrets.SOURCES__MTA_GTFS_STATIC__ZIP_URL }}
        run: |
          set -euo pipefail
          source .venv/bin/activate
          python -c "from dlt_mta_rtf import load_mta_pipeline as p; p.run(full_static=True)"
